baseURL = "http://example.org/"
languageCode = "en-us"
title = "Skye Blog"
theme = "purus"
enableEmoji = true

[taxonomies]

[permalinks]
  blog = "/:filename/"
	
[menu]
	[[menu.main]]
		name = "About"
		url = "/about"
		weight = -1
	[[menu.main]]
		name = "CV"
		url = "/CV"
		weight = 0
	[[menu.main]]
		name = "Blog"
		url = "/blog"
		weight = 1
	[[menu.main]]
		name = "Projects"
		url = "/projects"
		weigt = 2


[params]
	hometext = "Hey, how are you?"

#header set up 
[params.header]
	 name = "Skyler"
	 description = "This is my blog"
	 email = "skylerthomas0@gmail.com"


[markup]
    defaultMarkdownHandler = "blackfriday"

